version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: "config-server"
    hostname: "config-server"
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DB=consul
      - DBHOST=consul
      - DBPORT=8500
    depends_on:
      - consul
    volumes:
      - ./swagger.yaml:/app/swagger.yaml

  consul:
    image: hashicorp/consul:latest
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"
    volumes:
      - ./consul-volume:/consul/data

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"  # Expose Swagger UI on a different port
    environment:
      - SWAGGER_JSON=/app/swagger.yaml
    volumes:
      - ./swagger.yaml:/app/swagger.yaml:ro  # Mount swagger.yaml into the Swagger UI container
    depends_on:
      - server